---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[bash-it::default]
    attributes:
      bash-it:
        users:
          - root
